language: node_js
node_js:
  - 8

branches:
  only:
    - master

script:
  - npm test
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
  local-dir: dist

cache:
  directories:
    - node_modules
